txt:
  time_independent:
    128:
      train: "../data/predictions/txt/time_indipendent/train_pred_model-2025-03-12-embdim=None_time_independent_txt_mod4-epoch=019-val_combined_loss=0.3401_txt_dim=128_proj_emb_step=.zip"
      val:   "../data/predictions/txt/time_indipendent/val_pred_model-2025-03-12-embdim=None_time_independent_txt_mod4-epoch=019-val_combined_loss=0.3401_txt_dim=128_proj_emb_step=.zip"
    256:
      train: "../data/predictions/txt/time_indipendent/train_pred_model-2025-03-12-embdim=None_time_independent_txt_mod4-epoch=019-val_combined_loss=0.3401_txt_dim=256_proj_emb_step=.zip"
      val:   "../data/predictions/txt/time_indipendent/val_pred_model-2025-03-12-embdim=None_time_independent_txt_mod4-epoch=019-val_combined_loss=0.3401_txt_dim=256_proj_emb_step=.zip"
  lag1:
    128:
      train: "../data/predictions/txt/lag1/train_pred_model-2025-03-24-embdim=None_lag1_txt_mod4-epoch=023-val_combined_loss=0.3044_txt_dim=128_proj_emb_step=.zip"
      val:   "../data/predictions/txt/lag1/val_pred_model-2025-03-24-embdim=None_lag1_txt_mod4-epoch=023-val_combined_loss=0.3044_txt_dim=128_proj_emb_step=.zip"
    256:
      train: "../data/predictions/txt/lag1/train_pred_model-2025-03-24-embdim=None_lag1_txt_mod4-epoch=023-val_combined_loss=0.3044_txt_dim=256_proj_emb_step=.zip"
      val:   "../data/predictions/txt/lag1/val_pred_model-2025-03-24-embdim=None_lag1_txt_mod4-epoch=023-val_combined_loss=0.3044_txt_dim=256_proj_emb_step=.zip"
txtimg:
  time_independent:
    128:
      train: "../data/predictions/txtimg/time_indipendent/train_pred_model-2025-03-14-embdim=None_time_independent_txtimg_mod4-epoch=023-val_combined_loss=0.3322_txtimg_dim=128_proj_emb_step=.zip"
      val:   "../data/predictions/txtimg/time_indipendent/val_pred_model-2025-03-14-embdim=None_time_independent_txtimg_mod4-epoch=023-val_combined_loss=0.3322_txtimg_dim=128_proj_emb_step=.zip"
    256:
      train: "../data/predictions/txtimg/time_indipendent/train_pred_model-2025-03-14-embdim=None_time_independent_txtimg_mod4-epoch=023-val_combined_loss=0.3322_txtimg_dim=256_proj_emb_step=.zip"
      val:   "../data/predictions/txtimg/time_indipendent/val_pred_model-2025-03-14-embdim=None_time_independent_txtimg_mod4-epoch=023-val_combined_loss=0.3322_txtimg_dim=256_proj_emb_step=.zip"
  lag1:
    128:
      train: "../data/predictions/txtimg/lag1/train_pred_model-2025-03-16-embdim=None_lag1_txtimg_mod4-epoch=020-val_combined_loss=0.3004_txtimg_dim=128_proj_emb_step=.zip"
      val:   "../data/predictions/txtimg/lag1/val_pred_model-2025-03-16-embdim=None_lag1_txtimg_mod4-epoch=020-val_combined_loss=0.3004_txtimg_dim=128_proj_emb_step=.zip"
    256:
      train: "../data/predictions/txtimg/lag1/train_pred_model-2025-03-16-embdim=None_lag1_txtimg_mod4-epoch=020-val_combined_loss=0.3004_txtimg_dim=256_proj_emb_step=.zip"
      val:   "../data/predictions/txtimg/lag1/val_pred_model-2025-03-16-embdim=None_lag1_txtimg_mod4-epoch=020-val_combined_loss=0.3004_txtimg_dim=256_proj_emb_step=.zip"